name: Benchmark
on: pull_request
jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 6, 7, 8 ]
        symfony_yaml: [ 2, 3, 4, 5, 6 ]
        exclude:
          - php: 8
            symfony_yaml: 2
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Install dependencies
        run: |
          composer upgrade --with=symfony/yaml:${{ matrix.symfony_yaml }}
          pecl install yaml
      - name: Run benchmark
        run: |
          php -f ./benchmark.php
  
